version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - user-management
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=user_management
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis

  mysql:
    image: mysql:8.0
    container_name: user-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user_management
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
#    ports:
#      - "3306:3306"
    networks:
      - user-management

  redis:
    image: redis:7-alpine
    container_name: user-management-redis
    restart: unless-stopped
#    ports:
#      - "6379:6379"
    networks:
      - user-management

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: user-management-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8004:80"
    networks:
      - user-management
    depends_on:
      - mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: user-management-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - user-management

  nginx:
    image: nginx:alpine
    container_name: user-management-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - user-management
    depends_on:
      - app

networks:
  user-management:
    driver: bridge

volumes:
  mysql_data:
    driver: local
